### ISSUE TITLE
AttributeError: 'ParsedRequirement' object has no attribute 'match_markers'

### ISSUE THREAD

**Issue by jorti** [tonioo/sievelib#98] opened 2020-06-16 07:02 UTC
I get this error when building sievelib in Fedora rawhide with pip 20.1.x and Python 3.9.0b1

~~~
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
Traceback (most recent call last):
  File "/builddir/build/BUILD/sievelib-1.1.1/setup.py", line 38, in <module>
    INSTALL_REQUIRES = get_requirements(path.join(HERE, "requirements.txt"))
  File "/builddir/build/BUILD/sievelib-1.1.1/setup.py", line 31, in get_requirements
    if req.match_markers():
AttributeError: 'ParsedRequirement' object has no attribute 'match_markers'
~~~

Reported in Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1838484

**Comment by derula** [comment] 2020-06-17 22:25
Duplicate of #80 and fixed with #73, right? There just hasn't been a new release in a while.

@tonioo is there a roadmap for a new release, or anything the community could help with?

**Comment by tonioo** [comment] 2020-06-22 15:11
@derula I've been pretty busy those last months and I totally forgot to release 1.2.0! I guess we can release it once your current PR are all merged.

**Comment by derula** [comment] 2020-06-22 15:22
@tonioo do you think #99 should be held back for a 2.0 because of the BC break? Sounds good otherwise.

**Comment by tonioo** [comment] 2020-06-23 10:12
@derula No, I think it is time to drop python2 support.

**Closed** 2020-10-23 09:14 UTC
